version: "3.8"
services:
  app:
    container_name: niomwungeri-web-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/niomwungeri-web-api-db
      SPRING_DATASOURCE_USERNAME: niomwungeri-web-admin
      SPRING_DATASOURCE_PASSWORD: niomwungeri-web-password
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:15
    container_name: niomwungeri-web-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: niomwungeri-web-admin
      POSTGRES_PASSWORD: niomwungeri-web-password
      POSTGRES_DB: niomwungeri-web-api-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "niomwungeri-web-admin", "-d", "niomwungeri-web-api-db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: