name: API Build

on:
  push:
    paths:
      - 'api/**' # Trigger only if changes are in the 'api' directory

jobs:
  api-build:
    runs-on: ubuntu-latest
    name: Build API
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '23'

      - name: Build API
        run: |
          cd api
          mvn clean install

